apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: front-web
  template:
    metadata:
      labels:
        app: front-web
    spec:
      containers:
        - name: front-web
          image: 339712794622.dkr.ecr.ap-southeast-1.amazonaws.com/llw:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "50m"
          ports:
          - containerPort: 3000
          env:
          - name: API_GATEWAY_SERVICE_SERVICE_HOST
            value: api-gateway-service